@url = https://urshiftmate.onrender.com/user/config
@devUrl = http://localhost:8000/user/config


###
POST {{url}}/user/config/workplace
Content-Type: application/json

{

    "workplace": "PS",
    "hourlyRate": 11,
    "userId" : "6802a8e6a69534b1170d28a5"
}

###
GET {{url}}

###
GET {{url}}/create/setup


###
DELETE {{url}}devUrl/:workplaceId
